org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.4.18
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=netmusicbetterlogin
mod_name=Net Music: Better Login
mod_license=MIT
mod_version=1.0.1
mod_group_id=com.github.img
mod_authors=IMG
mod_description=A mod that provides a better login experience for Net Music.

netmusic_version_range=[1.5.0,)